mRemoteNG/mRemoteNG

- mRemoteV1/UI/Forms/frmMain.cs
> exception fixes

- CREDITS.TXT
- mRemoteV1/Resources/Language/Language.fr.resx
merge develop into release (again)
> merge develop into release (again)

- mRemoteV1/Connection/Protocol/ProtocolType.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Tools/ExternalTool.cs
- mRemoteV1/Tools/MiscTools.cs
- mRemoteV1/Tools/ReconnectGroup.Designer.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
- mRemoteV1/UI/Window/ConnectionWindow.cs
Merge latest 1.74 fixes into develop
> Merge latest 1.74 fixes into develop

- CHANGELOG.TXT
- InstallerProjects/Installer/Includes/Config.wxi
- InstallerProjects/Installer/mRemoteNGV1.wxs
Merge last 1.74 code changes into develop.
> MR-874: Added work-around to installer to ignore installation prereq

- mRemoteV1/Connection/Protocol/RDP/Connection.Protocol.RDP.cs
This code was just commented out, not sure if there was a reason for it originally, but I can't find anything wrong with this code. Reporter of MR-910 verified issue resolved with debug build.
> Fixes to support Remote Desktop Gateways

- _includes/navigation.html
> Merge bugs & feature requests

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds initail support for GitHub settings
> .github support

- mRemoteV1/Config/Connections/Multiuser/RemoteConnectionsSyncronizer.cs
- mRemoteV1/Config/Connections/Multiuser/SqlConnectionsUpdateChecker.cs
- mRemoteV1/Config/DataProviders/SqlDataProvider.cs
- mRemoteV1/Config/DatabaseConnectors/SqlDatabaseConnector.cs
- mRemoteV1/Config/Putty/PuttySessionsRegistryProvider.cs
- mRemoteV1/Config/Putty/PuttySessionsXmingProvider.cs
- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Container/ContainerInfo.cs
- mRemoteV1/Tree/ConnectionTreeModel.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
> Hunting for memory leaks

- mRemoteV1/Config/Serializers/XmlConnectionsSerializer.cs
> Reduce duplicate password serialization

- mRemoteV1/UI/Forms/frmMain.cs
> Make UI more responsive during save/load

- mRemoteNGTests/Connection/ConnectionInfoTests.cs
- mRemoteNGTests/IntegrationTests/XmlSerializationLifeCycleTests.cs
> Investigate password support for international chars

- mRemoteV1/Tree/Root/RootNodeTypeEnum.cs
- mRemoteV1/UI/Window/ConfigWindow.cs
- mRemoteV1/UI/Window/ConfigWindow.resx
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
> 240 config window buttons sometimes deactivate

- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
Feature existed in previous version - this fixes a feature regression
> Re-add double click support for toggling tree node expansion

- CHANGELOG.TXT
- CREDITS.TXT
- mRemoteV1/Properties/Settings.Designer.cs
- mRemoteV1/Properties/Settings.settings
- mRemoteV1/Resources/Language/Language.tr-TR.resx
- mRemoteV1/app.config
- mRemoteV1/mRemoteV1.csproj
Translation provided in forum post http://forum.mremoteng.org/viewtopic.php?f=9&t=3304&p=6583#p6583
> Add Turkish translation provided by forum user rizaemet

- InstallerProjects/Installer/CustomActions/SaveInstallLocation.wxs
- InstallerProjects/Installer/Fragments/DirectoriesFragment.wxs
- InstallerProjects/Installer/Fragments/MainExeFragment.wxs
- InstallerProjects/Installer/Fragments/MiscTextFilesFragment.wxs
- InstallerProjects/Installer/Fragments/PuTTYNGFragment.wxs
- InstallerProjects/Installer/Fragments/RegistryEntriesFragment.wxs
- InstallerProjects/Installer/Fragments/ShortcutFragment.wxs
- InstallerProjects/Installer/Installer.wixproj
- InstallerProjects/Installer/mRemoteNGV1.wxs
> make installer aware of previous install path

- CHANGELOG.TXT
- InstallerProjects/Installer/mRemoteNGV1.wxs
> Added prereq checks to non-gui executions

- mRemoteV1/Resources/Help/SSHFileTransfer.htm
This page provides HTML code for SSH File Transfer help page content. This documents the SSH File Transfer functionality of mRemoteNG and provides rudimentary troubleshooting information. 
Submitted in relation to issue #217
> Addition of HTML code for SSH File Transfer help page

- mRemoteV1/App/Runtime.cs
Connected to #280 
Only affects v1.75 beta 1
> Connections file corrupted when cancelling password prompt

- Tools/create_upg_chk_files.ps1
- mRemoteV1/App/Update/AppUpdater.cs
- mRemoteV1/App/Update/UpdateFile.cs
- mRemoteV1/App/Update/UpdateInfo.cs
check md5 for both zip and msi releases
> 284 md5 update checks

- README.MD
> Fix typo in README.MD

- CHANGELOG.TXT
- mRemoteV1/App/Runtime.cs
- mRemoteV1/Config/Settings/SettingsLoader.cs
- mRemoteV1/Tools/NotificationAreaIcon.cs
- mRemoteV1/UI/Forms/OptionsPages/AppearancePage.cs
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/UI/Window/ConnectionWindow.cs
- mRemoteV1/mRemoteV1.csproj
Simple changes, pushing up to 1.75
> 176 scheduled updates to 1.75

- mRemoteNGTests/Connection/DefaultConnectionInfoTests.cs
- mRemoteV1/Connection/DefaultConnectionInfo.cs
enum, int, bool -> string was throwing an exception. now using a simpler strategy for type conversion
resolves #295
> resolved issue where saving default con properties would fail

- mRemoteV1/App/Runtime.cs
- mRemoteV1/Config/Connections/ConnectionsSaver.cs
- mRemoteV1/Config/Putty/PuttySessionsRegistryProvider.cs
- mRemoteV1/Config/Putty/PuttySessionsXmingProvider.cs
- mRemoteV1/Config/Serializers/RemoteDesktopConnectionManagerDeserializer.cs
- mRemoteV1/Config/Settings/ExternalAppsLoader.cs
- mRemoteV1/Config/Settings/SettingsLoader.cs
- mRemoteV1/Config/Settings/SettingsSaver.cs
- mRemoteV1/Connection/Protocol/Http/Connection.Protocol.HTTPBase.cs
- mRemoteV1/Connection/Protocol/PuttyBase.cs
- mRemoteV1/Connection/Protocol/RDP/Connection.Protocol.RDP.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.cs
- mRemoteV1/UI/Forms/OptionsPages/UpdatesPage.cs
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/UI/Window/ComponentsCheckWindow.cs
- mRemoteV1/UI/Window/HelpWindow.cs
Cleanup any unneeded Convert.toSomething() calls.
> Cleanup converts

- CHANGELOG.TXT
- mRemoteNGTests/Config/Serializers/XmlConnectionNodeSerializerTests.cs
- mRemoteNGTests/Config/Serializers/XmlConnectionsDocumentCompilerTests.cs
- mRemoteNGTests/Config/Serializers/XmlConnectionsDocumentEncryptorTests.cs
- mRemoteNGTests/Config/Serializers/XmlConnectionsSerializerTests.cs
- mRemoteV1/Config/Serializers/XmlConnectionNodeSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionsDocumentCompiler.cs
- mRemoteV1/Config/Serializers/XmlConnectionsSerializer.cs
- mRemoteV1/Properties/AssemblyInfo.cs
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Merging hotfixes for v1.75 to master
> 1.75 hotfix 1

- mRemoteV1/Connection/Protocol/Http/Connection.Protocol.HTTP.cs
- mRemoteV1/Connection/Protocol/Http/Connection.Protocol.HTTPBase.cs
- mRemoteV1/Connection/Protocol/Http/Connection.Protocol.HTTPS.CertEvent.cs
- mRemoteV1/Connection/Protocol/Http/Connection.Protocol.HTTPS.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/mRemoteV1.csproj
> Gecko insecure certs v2

- mRemoteV1/UI/Controls/QuickConnectToolStrip.cs
- mRemoteV1/UI/Forms/frmMain.Designer.cs
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/UI/Forms/frmMain.resx
- mRemoteV1/UI/Menu/MainFileMenu.cs
- mRemoteV1/UI/Menu/ToolsMenu.cs
- mRemoteV1/UI/Menu/ViewMenu.cs
Some code refactoring to ensure that FrmMain Designer working in VS.
> Frmmain menus refactor option2

- CHANGELOG.TXT
- Tools/find_vstool.ps1
- Tools/postbuild_mremotev1.ps1
- Tools/set_LargeAddressAware.ps1
- Tools/verify_LargeAddressAware.ps1
This PR is for improving compatibility between build environments. Specifically, this improves support for VS2017.
> Improve compatibility with different build environments

- CHANGELOG.TXT
- mRemoteNGTests/Connection/ConnectionInfoTests.cs
- mRemoteNGTests/Container/ContainerInfoTests.cs
- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Container/ContainerInfo.cs
- mRemoteV1/Tree/ConnectionTreeModel.cs
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
> 530 fix tree node entry creation on exttool run

- mRemoteV1/Language/Language.ko-KR.resx
I'm good at using mReamoteNG.
Since there is no translation in Korean, we send you a translation file.
My full name is "Gyuha Shin"
Thanks
> Add Korean translation

- Jenkinsfile_publish.groovy
> jenkins release builds will now clean then build

- CHANGELOG.TXT
> changelog update

- mRemoteV1/Resources/Language/Language.de.resx
> German typo

- mRemoteV1/Resources/Language/Language.it.resx
Fixed spelling mistake in resource file.
> fixed italian spelling

- Jenkinsfile_publish.groovy
- Tools/create_upg_chk_files.ps1
- Tools/github_functions.ps1
- Tools/publish_draft_github_release.ps1
- Tools/publish_to_github.ps1
This improves the build pipeline:
- Jenkins will now build the UpdateCheck files for the respective channel
- small refactor of the github publishing scripts
> Improve publish automation

- mRemoteV1/UI/Controls/Base/NGButton.cs
- mRemoteV1/UI/Controls/Base/NGComboBox.cs
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
- mRemoteV1/UI/Window/SSHTransferWindow.cs
- Fixed bug in ngcombobox that wasnt rendering DisplayMember elements text in theme mode
- Change in ngbutton icon placement for long text button names
- Verify SSH and notifications file transfer for theme
- Changed ConnectionTree to elipse text based on the width of the panel
> fix theme ui

- mRemoteV1/Tools/ExternalToolArgumentParser.cs
> fallback to empty credentials settings in external apps

- mRemoteV1/Config/Settings/ExternalAppsLoader.cs
- mRemoteV1/Config/Settings/ExternalAppsSaver.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Tools/ExternalTool.cs
- mRemoteV1/UI/Controls/ExternalToolsToolStrip.cs
- mRemoteV1/UI/Window/ExternalToolsWindow.Designer.cs
- mRemoteV1/UI/Window/ExternalToolsWindow.cs
Refers to #152 
Added the "Show on Toolbar" option to the External Tools Dialog box.
Added the property to the ExternalTools object and defaulted the property to true for new tools. 
Added events to show the the changes immediately upon clicking the checkbox.
Added required code to support multiple languages BUT I did not update each language resource file..  unfortunately I'm not multilingual  :-(
> MR 152 add to external tools toolbar option

- mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
- mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.cs-CZ.resx
- mRemoteV1/Resources/Language/Language.de.resx
- mRemoteV1/Resources/Language/Language.es.resx
- mRemoteV1/Resources/Language/Language.fr.resx
- mRemoteV1/Resources/Language/Language.it.resx
- mRemoteV1/Resources/Language/Language.ja-JP.resx
- mRemoteV1/Resources/Language/Language.ko-KR.resx
- mRemoteV1/Resources/Language/Language.nb-NO.resx
- mRemoteV1/Resources/Language/Language.nl.resx
- mRemoteV1/Resources/Language/Language.pl.resx
- mRemoteV1/Resources/Language/Language.pt.resx
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Resources/Language/Language.ru.resx
- mRemoteV1/Resources/Language/Language.tr-TR.resx
- mRemoteV1/Resources/Language/Language.uk.resx
- mRemoteV1/Resources/Language/Language.zh-CN.resx
- mRemoteV1/Resources/Language/Language.zh-TW.resx
fix issue #797. Remove duplicated strings from all the .resx files as well
> issue #797 removed duplicate strings & fixed spelling

- mRemoteV1/Config/Putty/AbstractPuttySessionsProvider.cs
- mRemoteV1/Config/Putty/PuttySessionsRegistryProvider.cs
> fixed putty session name encoding - fixes #800

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Bumping up the quality of the templates with help from https://www.talater.com/open-source-templates
I figure more info is better than less
> Update .github templates

- mRemoteV1/Resources/Language/Language.es.resx
Fix a typo in Spanish language
> Update Language es

- mRemoteV1/Resources/Language/Language.ru.resx
> Update Language ru

- mRemoteV1/UI/Forms/frmMain.Designer.cs
- mRemoteV1/UI/Forms/frmMain.resx
- mRemoteV1/UI/Window/PortScanWindow.Designer.cs
- mRemoteV1/UI/Window/PortScanWindow.cs
- for the main form set the minimum resolution 1140; 603.
- for the form of port scans, done visual editing of components.
> Small visual correction of the forms

- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.de.resx
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/SecurityPage.cs
- mRemoteV1/UI/Forms/frmMain.Designer.cs
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/UI/Forms/frmOptions.cs
- mRemoteV1/UI/Menu/ViewMenu.cs
some changes regarding tranlsation
> Translation

- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Resources/Language/Language.ru.resx
- change (Language.ru.resx)
- change (Language.resx)
> Update the Russian language

- mRemoteV1/Resources/Language/Language.zh-CN.resx
Only chinese simplified language update.
> Chinese simplified language update for latest commit 05c96da

- mRemoteV1/Connection/ConnectionsService.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Controls/ConnectionContextMenu.cs
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Feature Request: Right click option to copy hostname #1141
> Feature Request: Right click option to copy hostname #1141

- mRemoteV1/App/ProgramRoot.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Forms/UnhandledExceptionWindow.Designer.cs
- mRemoteV1/UI/Forms/UnhandledExceptionWindow.cs
- mRemoteV1/UI/Forms/UnhandledExceptionWindow.resx
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/mRemoteV1.csproj
Implements #1123 
A window will be shown when an unhandled exception occurs
Manual testing
> Added unhandled exception window

- mRemoteV1/Connection/ConnectionInitiator.cs
- mRemoteV1/Connection/Protocol/ICA/IcaProtocol.cs
- mRemoteV1/Connection/Protocol/ProtocolBase.cs
- mRemoteV1/Connection/Protocol/RDP/RdpErrorCodes.cs
- mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
- mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
Host names are now displayed in notifications when appropriate (disconnections, protocol errors).
#929
Manual testing to ensure message are helpful
> Host names are now displayed in some notifications

- mRemoteV1.sln
- mRemoteV1/UI/Window/ConnectionTreeWindow.Designer.cs
See #1216 
This is what it looks like:
> Moved searchbar in connection tree to top

- mRemoteV1/Properties/Settings.Designer.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.de.resx
- mRemoteV1/Resources/Language/Language.en-US.resx
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Settings.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.resx
- mRemoteV1/UI/Forms/frmMain.Designer.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.Designer.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
> Position of search bar configurable via settings

- CREDITS.TXT
- mRemoteV1/App/ProgramRoot.cs
- mRemoteV1/UI/Forms/FrmSplashScreen.Designer.cs
- mRemoteV1/UI/Forms/FrmSplashScreen.cs
- mRemoteV1/UI/Forms/FrmSplashScreen.resx
- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/mRemoteV1.csproj
Implemented a splash screen as suggested in #949
> Splashscreen

- mRemoteNGTests/UI/Controls/SecureTextBoxTestForm.Designer.cs
- mRemoteNGTests/UI/Controls/TestForm.Designer.cs
- mRemoteNGTests/UI/Controls/TextBoxExtensionsTestForm.Designer.cs
- mRemoteV1/Connection/InterfaceControl.Designer.cs
- mRemoteV1/Tools/ReconnectGroup.Designer.cs
- mRemoteV1/UI/Controls/Base/NGComboBox.cs
- mRemoteV1/UI/Controls/CredentialRecordListView.Designer.cs
- mRemoteV1/UI/Controls/CredentialRepositoryListView.Designer.cs
- mRemoteV1/UI/Controls/NewPasswordWithVerification.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/AdvancedPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/AppearancePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/CredentialsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/NotificationsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/OptionsPage.cs
- mRemoteV1/UI/Forms/OptionsPages/SecurityPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/SqlServerPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/StartupExitPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/TabsPanelsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ThemePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/UpdatesPage.Designer.cs
- mRemoteV1/UI/Forms/frmChoosePanel.Designer.cs
> Hidpi fixes

- mRemoteV1/UI/Forms/frmMain.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
Fixes #1230. I didn't implement an option for this feature because I didn't want to delay it for translation and I wasn't sure of the best way to insert a new option. I don't know if it is desired to insert it into the existing list somewhere around another similar option or just append it to the bottom.
> Tracks the active tab in the treeview

- mRemoteV1/App/Windows.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Menu/ViewMenu.cs
> Jump to menu

- mRemoteV1/Tools/ExternalTool.cs
- mRemoteV1/UI/Controls/ConnectionContextMenu.cs
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Added new feature for old issue opened in 2017 (ability to run External tools on folders) and fixed small bug with copy hostname function.
Tested manually with different languages.
>  Added ability to run External tools on folders

- mRemoteV1/Config/Serializers/MiscSerializers/RemoteDesktopConnectionDeserializer.cs
Fixes #1293 
Added missing properties to RemoteDesktopConnectionDeserializer.
> added missing properties when deserializing .rdp file

- mRemoteV1/Resources/Language/Language.zh-CN.resx
Correct the Chinese translation in https://github.com/mRemoteNG/mRemoteNG/issues/1403
> Correct the Chinese translation in https://github.com/mRemoteNG/mRemoteNG/issues/1403

- CHANGELOG.md
- mRemoteV1/Resources/Language/Language.nb-NO.resx
Updated Norwegian translation
New version of Language.nb-NO.resx
Ran project in Visual Studio 2017
> Updated Norwegian translation

- CHANGELOG.md
- mRemoteV1/Resources/Language/Language.zh-CN.resx
update chinese simplified language base on commit 9fdcffd
> update chinese simplified language base on commit 9fdcffd

- CHANGELOG.md
- mRemoteV1/App/Initialization/StartupDataLogger.cs
Optimized the WMI query in `mRemoteNG.App.Initialization.StartupDataLogger::GetArchitectureData()`
Update to the WMI query significantly reduces execution time of the GetArchitectureData() method proportionally to the number of CPUs available within the system.
The issue is described in #1468 
Speed up loading time
I have only tested the WMI query. Due to the scope of the change, other testing doesn't seem to be necessary
> Improve startup time

- mRemoteV1/Resources/Language/Language.zh-CN.resx
update chinese simplified language base on commit 3acb9f1.
- [ x ] Updated translation
> update chinese simplified language 2019/06/13

- mRemoteV1/Resources/Language/Language.zh-CN.resx
update chinese simplified language 2019/07/23
- [ x ] Updated translation
> update chinese simplified language 2019/07/23

- mRemoteV1/Resources/Language/Language.pl.resx
Add translations for Polish language for Settings -> Notifications panel
Translations were missing
Compare with other applications, run check spelling
> Add translations for Polish language

- mRemoteV1/Config/Serializers/ConnectionSerializers/MsSql/DataTableDeserializer.cs
Table allows for null values which must be handled so as not to create an error
Added condition so that if the data row column "RdpVersion" has a null value it is ignored without causing an error.
When I tried to run the application in debug mode linked to MsSql, the data table had been changed with two additional columns; [RdpVersion], [InheritRdpVersion]
fixing the MsSql table manually by issuing the commands;
```
alter table tblCons add [RdpVersion] [varchar] (10) NULL
alter table tblCons add [InheritRdpVersion] [bit] NOT NULL DEFAULT 0
```
This then caused the an exception on the line
`if (Enum.TryParse((string)dataRow["RdpVersion"], true, out RdpVersion rdpVersion))`
Added columns to MsSql table, added condition to code to retrieve the column value if not null
Re-run application …
> Update DataTableDeserializer.cs handle null values in column RdpVersion

- CREDITS.md
- mRemoteV1/UI/Window/AboutWindow.cs
On clicking somewhere there isn't a link in the CREDITs/Change Log controls caused an exception as there wasn't a clickable link.
When clicking a bit of text in either of the controls gwbChangeLog, gwbCredits caused an exception.
Stops the exception occurring
Help / About, click any text that isn't a url, no longer causes an exception.
Amended the CREDITS.md where github.com addresses were used shown, replaced with http://github.com (although could be changed to https)
- Bug fix (non-breaking change which fixes an issue)
> Fix about window click, updated CREDITS.md

- CREDITS.md
- mRemoteV1/Resources/Language/Language.uk.resx
I translate all untranslated strings and fix errors
I've been trying to test it by following instruction. But UI been always in English.
**So, need help with testing!**
> Update Ukrainian translation

- mRemoteV1/App/Info/ConnectionsFileInfo.cs
Set ConnectionsFileInfoSql.ConnectionFileVersion from 2.7 to 2.8 after #1669
> ConnectionFileVersion from 2.7 to 2.8

- mRemoteV1/Resources/Language/Language.fr.resx
I had changed the word "Crypter" by "Chiffrer" because the word "Crypter" does not exist in french.
The correct word is "Chiffrer"
A translation error that i have to correct
I have not tested the change
- Updated translation
> Change "Crypter" to "Chiffrer"

- mRemoteNG/Resources/Language/Language.ru.resx
Fix for incorrect russian translation.
> Fix incorrect russian translation

- mRemoteNG/Resources/Language/Language.de.resx
> Update German translations

- mRemoteNG/Tools/IeBrowserEmulation.cs
> Fix Portable version build failed

- mRemoteNG/Tree/ConnectionTreeDragAndDropHandler.cs
- mRemoteNG/UI/Window/ConnectionTreeWindow.Designer.cs
I would like to enable the possibility to drag&drop multiple items from one place to another
Feature just to move multiple items, not to edit all at the same time
> Enable multi items drag&drop

- CHANGELOG.md
- mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer26.cs
- mRemoteNG/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionNodeSerializer27.cs
- mRemoteNG/Connection/Protocol/ProtocolFactory.cs
- mRemoteNGTests/Config/Serializers/ConnectionSerializers/Xml/XmlConnectionsSerializerTests.cs
Config.xml files become too large even if inheritance is not used. 
#1850 
I created a small sample config with 2 connections, which was 8 kb. Then I serialized with my version, now it is 4 kb.
> feature/minify_xml - Minifying xml config file

- mRemoteNG/Documentation/external_tools_cheat_sheet.rst
Added Powershell example connecting to a remote host using credentials saved in mRemoteNG. Took me several hours to figure out how to do this without a password prompt. Extremely helpful indeed. Also a good showcase on how to use mRemoteNG variables.
Other edits: Powershell (ISE) link was obsolete leading to 404, provided a new one. Added description to IE instead of a dummy.
> Powershell (non ISE) added to common external tools with a handful argument. Several edits.
