- mRemoteNGTests/Connection/ConnectionInfoTests.cs
- mRemoteNGTests/Connection/Protocol/ProtocolListTests.cs
- mRemoteNGTests/mRemoteNGTests.csproj
- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Connection/Protocol/ProtocolList.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
Implemented INotifyCollectionChanged in ProtocolList and hooked those events up to the ConnectionInfo.PropertyChanged event. The TreeListview will refresh the tree node when it receives a a notice that the OpenConnections property has changed (its list contents have changed, to be specific.)
This resolves #141
> Connection icon not updating until mouseover

- mRemoteV1/Config/Serializers/DataTableDeserializer.cs
- mRemoteV1/Config/Serializers/DataTableSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionNodeSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionsDeserializer.cs
- mRemoteV1/Connection/AbstractConnectionInfoData.cs
- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Connection/ConnectionInfoInheritance.cs
- mRemoteV1/Connection/Protocol/RDP/Connection.Protocol.RDP.cs
- mRemoteV1/Properties/Settings.Designer.cs
- mRemoteV1/Properties/Settings.settings
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Schemas/mremoteng_confcons_v2_6.xsd
- mRemoteV1/UI/Window/ConfigWindow.cs
- mRemoteV1/app.config
Allow users to configure a number of minutes until the session will automatically disconnect them for inactivity.
> RDP Optional Minutes to Idle Timeout

- mRemoteV1/UI/Forms/frmMain.cs
Fix for #369 
Reset Layout will now hide the notification pane (if it's opened) and dock it to it's default place (if it's been moved). I've tested this by floating the notification pane, and then resetting the layout. It seems to match its default behavior on initial launch with no preexisting pnlLayout.xml config.
> Quick fix for #369 (Reset Layout Ignores Notification Pane)

- mRemoteV1/Config/Serializers/XmlConnectionNodeSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionsDeserializer.cs
- mRemoteV1/Schemas/mremoteng_confcons_v2_6.xsd
The unique connectioninfo id is now being serialized to the confCons file. This enables us to tie serialized objects to their inflated instances in memory.
This change was made to support the credential manager feature being developed for v1.76.
> Serialize connectioninfo ID

- mRemoteV1/Config/Serializers/DataTableDeserializer.cs
- mRemoteV1/Config/Serializers/DataTableSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionNodeSerializer.cs
- mRemoteV1/Config/Serializers/XmlConnectionsDeserializer.cs
- mRemoteV1/Connection/AbstractConnectionInfoData.cs
- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Connection/ConnectionInfoInheritance.cs
- mRemoteV1/Connection/Protocol/RDP/Connection.Protocol.RDP.cs
- mRemoteV1/Properties/Settings.Designer.cs
- mRemoteV1/Properties/Settings.settings
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Schemas/mremoteng_confcons_v2_6.xsd
- mRemoteV1/UI/Window/ConfigWindow.cs
- mRemoteV1/app.config
Added an option to alert the user if they were disconnected due to inactivity. Additionally, if the user specifies a number of minutes to idle that is above the maximum, it will set the number of minutes to idle at the max (used to be that it would set the minutes to idle to zero or never idle out).
_This is continued off of PR #342 and ticket #221_
> RDP Minutes to Idle Timeout - Update 4

- mRemoteV1/Resources/Language/Language.cs-CZ.resx
- mRemoteV1/app.config
The file was translated from the original Language.resx at the state of the current branch "develop", the main app.config was altered also. Just to not forget a few notes (maybe I might correct them later in a different branch/pull request):
Help (menu) -> Announcments (menu item) is not localized
Help (tab) -> tab title „Help“ is not localized according to the menu item „Help“
Tabs right click context menu -> Rename -> rename Dialogue -> OK/Cancel buttons are not localized accroding to the „strButtonOK“ „strButtonCancel“
Options (Settings) dialogue -> Tabs & Panels -> Use only Notifications panel (no messagbox popups) checkbox is not localized
Options (Settings) dialogue -> Advanced -> Write log file (mRemoteNG.log) checkbox is not localized
Components check tab -> Gecko (Fireforx) …
> Develop added czech loc

- Jenkinsfile_publish.groovy
jenkinsfile_publish.groovy contained a hard coded branch build reference that was used for testing. this is now using build params from jenkins.
> fixed hard coded branch names in jenkinsfile_publish

- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Resolves issue #479.  When right clicking Connections => New Node or New Folder the new item should start in editing mode so that it can be named immediately without additional clicks.
> Added a BeginEdit() at the end of the AddNode function.

- mRemoteV1/Config/Serializers/Versioning/XmlCredentialManagerUpgrader.cs
- mRemoteV1/UI/Forms/CredentialManagerUpgradeForm.cs
The configuration version was parsed in the credential manager upgrade
process using the current user culture and crashed on cultures where '.'
isn't the decimal separator.
> Credential manager upgrade crash

- mRemoteNGTests/Tree/NodeSearcherTests.cs
- mRemoteV1/Tree/NodeSearcher.cs
This pull request is to cover the below feature request:
https://github.com/mRemoteNG/mRemoteNG/issues/184
Minor changes to search the hostname and description field of the connection, instead of just the connection name.
Also added the following three tests:
SearchByDescriptionReturnsAllExpectedMatches
SearchByDescription1ReturnsAllExpectedMatches
SearchByHostnameReturnsAllExpectedMatches
All tests passed after the changes.
Please also note the search performance might be slow due to tree not being indexed but I think it should be sufficient.
> Added extra logic to search the hostname and description fields of the connection instead of just the name.

- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
This prevents double clicks (and anything else but the rename context menu) from trying to edit a tree view item. Effectively stops #550.
This isn't as clean as just setting `LabelEdit = false`, but that would also disable the Rename context menu.
> Issue #550 Fix - Don't propagate edit if it didn't come from the menu item

- mRemoteV1/App/Logger.cs
Under Options -> Advanced, the option Write log file (mRemoteNG.log) is simply ignored when attempting to create the file.
Setting the log file path to null seems to work as intended. But it requires a program restart, maybe a warning for that?
Reported in [issue #536](https://github.com/mRemoteNG/mRemoteNG/issues/536).
> Prevented log file creation when writeLogFile option is not set

- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
This is reported in [issue#665](https://github.com/mRemoteNG/mRemoteNG/issues/665) and is actually weird just returning, and leaving the user to guess what happened.
My proposal is just to create on the root node if no node was selected; KeePass does the same, I don't find very friendly, but my is its better than doing literally nothing.
There you go, if anyone has a more user friendly solution I'll go for it.
> Fix proposal for issue 'Can not add new connection or new folder'

- mRemoteV1/App/Startup.cs
When launching the application for the first time, the settings actually assume the configured default values, which in turn overrides any setting we set before `Application.Run()`; unless we [force save](https://github.com/mRemoteNG/mRemoteNG/compare/Patch9...pedro2555:676?expand=1#diff-14048bc5d1a12b28dc053ffa640f3f19R314)
Fixes #676
> First startup ignores cons param

- mRemoteV1/App/Startup.cs
- mRemoteV1/UI/Forms/frmMain.cs
Potential resolution to one of the problems brought up in #482 
Rearranged some program initialization code to ensure the ConDefaultPassword property in the Settings class is decrypted before it is assigned to the singleton DefaultConnectionInfo which is used through the app.
> Default connection password must be decrypted before first use

- mRemoteV1/Connection/Protocol/IntegratedProgram.cs
- mRemoteV1/Tools/ExternalTool.cs
I've noticed #649 myself, when integration cli apps. There was a bunch of swapped names and paths that I fix here.
But, from all I could try [this little change](https://github.com/mRemoteNG/mRemoteNG/compare/Patch9...pedro2555:issue%23649-cannot-integrate-cli-apps?expand=1#diff-c5eb9dabf670787a86a2a706864efecfL66), that seems super dangerous, allows both cli apps to integrate correctly and I could not find an app that could break this.
I've tried blaming that line back in the tree, but got far too deep to continue (6b4f2d3).
> Fixed integrated cli apps?

- mRemoteV1/App/Runtime.cs
- mRemoteV1/Config/Connections/Multiuser/SqlConnectionsUpdateChecker.cs
Made Runtime.LastSqlUpdate public and set the connectionTree update to happen only if the user is not the last updater
> Fixed #529

- mRemoteV1/Config/Putty/PuttySessionsXmingProvider.cs
The issue was that the FileSystemWatcher for the Putty Sessions (non-portable) was being initiated on a path that didn't exist, so an exception was being thrown.  I added a check to determine if the path exists before the FileSystemWatcher is initiated.
The other issue is that the full path of putty.exe was being combined with the Putty.conf and created an incorrect path.  (var puttyConfPath = "path_to_exe\PuTTYNG.exe\putty.conf").   I modified the statement to only combine the folder of the exe to the conf file.
> MR-747 putty sessions.watcher.start watching failed. not found

- mRemoteV1.sln
- mRemoteV1/UI/Forms/OptionsPages/AppearancePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/AppearancePage.resx
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.cs
- mRemoteV1/UI/Forms/OptionsPages/CredentialsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/NotificationsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/NotificationsPage.resx
- mRemoteV1/UI/Forms/OptionsPages/OptionsPage.cs
- mRemoteV1/UI/Forms/OptionsPages/SecurityPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/StartupExitPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/StartupExitPage.resx
- mRemoteV1/UI/Forms/OptionsPages/TabsPanelsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ThemePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/UpdatesPage.Designer.cs
Rearranged some elements from the settings to prevent that translated strings overlap with these elements. Issue #784
> Rearranged settings elements

- mRemoteV1/UI/Forms/OptionsPages/AdvancedPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/AppearancePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/CredentialsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/NotificationsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/SecurityPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/SqlServerPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/SqlServerPage.resx
- mRemoteV1/UI/Forms/OptionsPages/StartupExitPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/TabsPanelsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ThemePage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/UpdatesPage.Designer.cs
- mRemoteV1/UI/Forms/frmOptions.Designer.cs
Small layout fixes to frmOptions and option pages:
_-unified button heights
-fixed tab order on some option pages elements
-resized "Launch PuTTY"-button under  Options>Advanced to display PuTTY Icon in full size
-resized main panel in frmOption to fit size of option panes
-reduced size of bottom panel in frmOptions to waste less space
-fixed distance to form border of"OK" and "Cancel" buttons in frmOptions
-unified all border styles of panels in frmOptions to none. (This makes the design look a little bit more flat and cleaner, also removes the strange edge  in the title bar where the two panels meet)
-set width of deviders on frmOptions to 1px (also looks a lot cleaner)
-fixed alignment of some elements in options_
Some of these changes can be seen in the screenshots:
**Before:** …
> Further design optimizations on settings

- mRemoteV1/Config/Settings/ExternalAppsLoader.cs
- mRemoteV1/Config/Settings/SettingsSaver.cs
- mRemoteV1/Tools/ExternalTool.cs
- mRemoteV1/UI/Window/ExternalToolsWindow.Designer.cs
- mRemoteV1/UI/Window/ExternalToolsWindow.cs
- mRemoteV1/UI/Window/ExternalToolsWindow.resx
I'm closing #207 and as far as code goes, this is pretty much whats missing; can even be merged straight away with no backward compatibility issues.
But I'm unsure about 2 things:
1. What is `argParser.ParseArguments()` supposed to do? (I've peeked at the code, and it's no easy guess)
2. This, of course, would required adding UI elements to expose this, but just stumbled on [this bit of code](https://github.com/mRemoteNG/mRemoteNG/blob/Patch9/mRemoteV1/UI/Window/ExternalToolsWindow.cs#L196). My intention is to add a new input exactly as there is for _Arguments_, does this require any coordination or how does it work with the internationalisation part? (kinda lost here)
> [RFC] Added support for custom working directory in External Tool

- CHANGELOG.TXT
- mRemoteV1/Properties/Settings.Designer.cs
- mRemoteV1/Properties/Settings.settings
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTreeSearchTextFilter.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.Designer.cs
- mRemoteV1/UI/Forms/OptionsPages/ConnectionsPage.cs
- mRemoteV1/UI/Window/ConnectionTreeWindow.cs
- mRemoteV1/app.config
- mRemoteV1/mRemoteV1.csproj
Partially implements #338 
Implementation is done, though there is a caveat to the filtering at the moment. Filtering only considers items that are currently expanded. If a folder is collapsed, its children are not considered in filtering. We should revisit this feature later to remove this flaw
> Implemented connection search filtering feature

- mRemoteV1/UI/Controls/ConnectionTree/ConnectionTree.cs
Added not null condition to method RenameSelectedNode
When I have no selected node and I press F2 key, NullReferenceException appears in method RenameSelectedNode(). I added not null condition.
Downloaded develop branch, fixed bug and tested in VS2017
> Fixing NullReferenceException when renaming node

- Jenkinsfile_publish.groovy
- Tools/github_functions.ps1
- Tools/postbuild_mremotev1.ps1
- Tools/tidy_files_for_release.ps1
- Tools/zip_portable_files.ps1
- Tools/zip_symbols.ps1
- mRemoteV1/mRemoteV1.csproj
We now emit and archive debug symbols for released versions of mRemoteNG. This will help with debugging issues from the field.
3 changes were made in this PR:
1. Release/Release Portable build configurations now create PDB files.
1. The post build process was modified to zip debug symbols
1. The jenkins file for release builds was updated for msbuild 15 (ported over changes from the normal jenkins file which was updated a while ago).
Implements requested build change in #647
Created several draft releases via the `Build mRemoteNG for release` job. All assets were included as expected in the release draft on GitHub.
> 647 save symbols

- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/Resources/Language/Language.ru.resx
- mRemoteV1/UI/Window/ConnectionWindow.Designer.cs
- mRemoteV1/UI/Window/ConnectionWindow.cs
In connection tab context menu added 2 new items: "Disconnect Other Tabs" and "Disconnect Tabs To The Right"
It is problematic to close many tabs one by one if you need to close not ALL tabs.
Tested by hand. Sorry, I don't know how to test this automatically.
> Add context menu items to close other and other to the right tabs

- mRemoteV1/Config/Connections/SaveConnectionsOnEdit.cs
Fixes #1139
The method SaveConnectionOnEdit now queries the IsClosing property of FrmMain and thereby a saving is prevented. When opening a connection, the SaveConnectionOnEdit method now saves the status and does not overwrite it when closing mRemoteNG.
The Option "Reconnect to previously opened sessions on startup" is not working if "Save connections after every edit" is enabled. This is because the connection settings are saved again after the connection is closed and thereby the connection is saved as "not connected".
Running the portable version.
> Fixing "Reconnect to previously opened sessions on startup"

- Tools/CreateBulkConnections_ConfCons2_6.ps1
The bulk connections PowerShell script currently doesn't work as it references non-existent classes (presumably from an old class structure). This PR fixes the issue by using the new classes. A lot of the script has been re-written to adhere to PowerShell best practices and to paramterize a lot of the .Net methods. The changes are:
- Remove trailing whitespaces per the [PowerShell community best practices](https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Code-Layout-and-Formatting.md#trailing-spaces).
- Query the registry for the install path instead of requiring the end user to edit the script
- Update the syntax for instantiating objects from .Net classes from the old `New-Object` syntax.
- Rename functions using a shorter naming convention
- Add parameters …
> Fix and refactor CreateBulkConnections_ConfCons2_6.ps1

- mRemoteV1/UI/Controls/QuickConnectToolStrip.cs
This fixes #1271.
Changing the protocol in the quick connect toolstrip sets the focus to the textbox instead of directly connecting.
Users that use the keyboard can still initiate a connection when hitting `ENTER` afterwards.
> Set focus to textbox instead of connecting, 

- mRemoteV1/Connection/ConnectionInfo.cs
- mRemoteV1/Connection/Protocol/ISupportsViewOnly.cs
- mRemoteV1/Connection/Protocol/RDP/RdpProtocol.cs
- mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
- mRemoteV1/Resources/Language/Language.Designer.cs
- mRemoteV1/Resources/Language/Language.de.resx
- mRemoteV1/Resources/Language/Language.resx
- mRemoteV1/UI/Controls/ConnectionContextMenu.cs
- mRemoteV1/UI/Window/ConnectionWindow.cs
- mRemoteV1/mRemoteV1.csproj
This implements #896
Adds a View Only mode to RDP connections. When enabled, the activex control does not send mouse or keyboard input to the remote server. This mode can be activated in 2 ways:
- through the connection info context menu under `Connect with Options` -> `Connect in View Only mode`
- through the connection tab context menu `View Only` toggle button. This button was previously only available to VNC connections - it is now available for RDP as well
2 localizations have been changed:
- `ConnectInViewOnlyMode` was added
- `strMenuViewOnly` was changed from "View Only (VNC)" to "View Only"
This can be useful if you have some automated work being done on the remote machine (like automated UI testing) that needs control of the mouse/keyboard, but you don't want to accidentally …
> Implemented a view only mode for RDP

- CHANGELOG.md
- mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
Added code to report within 150ms a timeout error if no connection can be made on the VNC port for 150ms. 
When attempting to make a VNC connection to a host that is off or does not have VNC installed will result in that the application will hang for 20-30 seconds, because it attempts to connect to the host for 20-30 seconds before continuing with the program. I have used a call back method with a test connection to test the connection to the host using the user configured VNC port, and if the command runs for more than 150ms it will through a connection timeout error.  
It has been annoying for us when attempting to connect to a host that is off and then the application hangs for 20-30 seconds before we can continue with a next connection. The code with the call back method I have added …
> Handle VNC timeout

- mRemoteV1/Connection/Protocol/VNC/Connection.Protocol.VNC.cs
It has been found at times that when connecting to a VNC host, the connection times-out even if the host is powered on. This happens mostly when you are connected to the network through WiFi. This means that when executing the code the test connection takes at times more than the current set 150ms to test the connection to the host and as a result gives an timeout error.
The time out value for the VNC test connection has been increased from 150ms to 500ms.
It has been tested making various VNC connections from a PC that is connected to the network through WiFi. No timeout errors accorded when connecting to any of the hosts.
> Increased VNC test connection timeout from 150ms to 500ms

- CHANGELOG.md
- mRemoteV1/Connection/Protocol/RDP/RdpProtocol6.cs
Previously DisableRdpdr was used, which broke smartcard and sound redirection.
By changing it to use AdvancedSettings6.RedirectClipboard, it works without breaking other stuff.
The problem was introduced in this PR: #951
This change fixes the following issues: #1465, #1632, #1713
I have tested with the 1.77.1 build without the change, and if clipboard redirection is set to No, drives and sound is broken - setting it to Yes and they work.
With this change they work with the Clipboard setting set to both Yes and No.
I have also tested that the clipboard setting is working, setting it to No results in the clipboard not being carried across, setting it to Yes, and it does.
Bug fix
> Corrected how clipboard redirection is done

- CHANGELOG.md
- mRemoteNG/Connection/Protocol/RDP/RdpProtocol6.cs
RDP remote desktop scale was calculated incorrectly, resulting in local 125%/150% translating to remote 100%
When working with a high-DPI display with a scaling factor, the remote machines are set to 100% due to this bug. This results in RDP session where everything is too small.
#1427 RDP doesn't respect desktop scaling
Tested on my 125%-scale setup: laptop monitor of 1920*1080 and + 4K external monitor. My change works great on both monitors.
This change is a one-liner, only in the RDP connection, so I believe it's low-risk.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
- [ x ] All Tests within VisualStudio are passing
- [ x ] I have updated the changelog file …
> Fix RDP local desktop scale not taking effect on remote
